services:
  web:
    build: .
    command: >
      bash -c "python manage.py migrate --noinput && python manage.py csu && python manage.py collectstatic --noinput && gunicorn task_tracker.wsgi:application --bind 0.0.0.0:8000"
    environment:
      - DEBUG=False
      - DATABASE_HOST=db
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    expose:
      - "8000"
    depends_on:
      - db
      - redis
    env_file:
      - ./.env

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/staticfiles
    depends_on:
      - web

  db:
    image: postgres:16
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: "redis:7"
    env_file:
      - ./.env
    volumes:
      - redis_data:/data

networks:
  default:

volumes:
  postgres_data:
    driver: local
  static_volume:
    driver: local
  redis_data:
    driver: local
