# Generated by Django 5.2.5 on 2025-08-23 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "fullname",
                    models.CharField(
                        help_text="Укажите полное имя сотрудника", max_length=255, verbose_name="Полное имя сотрудника"
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        help_text="Укажите должность сотрудника", max_length=255, verbose_name="Должность сотрудника"
                    ),
                ),
            ],
            options={
                "verbose_name": "Сотрудник",
                "verbose_name_plural": "Сотрудники",
                "ordering": ["fullname"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Укажите наименование задачи", max_length=255, verbose_name="Наименование задачи"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Укажите подробности задачи", null=True, verbose_name="Описание задачи"
                    ),
                ),
                (
                    "period",
                    models.DateTimeField(
                        help_text="Укажите срок выполнения задачи", verbose_name="Срок выполнения задачи"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Open", "open"),
                            ("To Do", "to do"),
                            ("In Progress", "in progress"),
                            ("Done", "done"),
                            ("Reopened", "reopened"),
                            ("Closed", "closed"),
                        ],
                        default="open",
                        help_text="Выберите статус задачи",
                        verbose_name="Статус задачи",
                    ),
                ),
                (
                    "executor",
                    models.ForeignKey(
                        help_text="Выберите исполнителя задачи",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tasks.employee",
                        verbose_name="Исполнитель задачи",
                    ),
                ),
                (
                    "parent_task",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите родительскую задачу",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_tasks",
                        to="tasks.task",
                        verbose_name="Родительская задача",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача",
                "verbose_name_plural": "Задачи",
                "ordering": ["name", "executor", "status"],
            },
        ),
    ]
