# Generated by Django 5.2.5 on 2025-08-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_alter_task_executor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("Open", "open"),
                    ("To Do", "to do"),
                    ("In Progress", "in progress"),
                    ("Done", "done"),
                    ("Reopened", "reopened"),
                    ("Closed", "closed"),
                ],
                default="Open",
                help_text="Выберите статус задачи",
                verbose_name="Статус задачи",
            ),
        ),
    ]
